---
title: Dave Dawson • Creative director, website, and product designer in California
timezone: UTC
meta-description: I create digital products & websites for progressive organizations
meta-image: /img/share/global-share-graphic.png
url: https://www.iamdavedawson.com