---
title: Dave Dawson
timezone: UTC
meta-description: I create digital products & websites for progressive organizations
meta-image: /img/share/global-share-graphic.png
url: https://www.iamdavedawson.com